app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique = True)
    hash_pass = db.Column(db.String(255))
    blogs = db.relationship('Blog', backref = 'user', lazy = "dynamic")
    comments = db.relationship('Comment', backref = 'user', lazy = "dynamic")
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    @property
    def password(self):
        raise AttributeError("You cannot read password attribute")

    @password.setter
    def password(self, pass_entry):
        self.hash_pass = generate_password_hash(pass_entry)

    def verify_password(self, pass_entry):
        return check_password_hash(self.hash_pass, pass_entry)

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self.id

    def __repr__(self):
        return f'User {self.username}::{self.id}'

class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String())
    content = db.Column(db.String())
    created_at = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref = 'blog', lazy = "dynamic")


    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @staticmethod
    def get_user_blogs(user_id):
        return Blog.query.filter_by(user_id = user_id).all()

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key= True)
    content = db.Column(db.String())
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self.id
        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField, SubmitField,TextAreaField,BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from wtforms.validators import Required


class CommentForm(FlaskForm):
    title = StringField('Comment title', validators = [Required()])
    comment = TextAreaField('Comment review')
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):
    title = StringField('Blog title', validators = [Required()])
    content = TextAreaField('Blog content', validators = [Required()])
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')    

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')    

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()

photos = UploadSet('photos',IMAGES)
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

     # configure UploadSet
    configure_uploads(app,photos)


    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # from .requests import configure_requests
    # configure_request(app)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask_login import login_required,current_user
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User,Blog,Comment
from .. import db,photos
from datetime import datetime
from ..requests import get_quote
from .forms import BlogForm,CommentForm,UpdateProfile,PostForm





@main.route('/')
def index():
    quote = get_quote()
    tittle='blog-app'
    return render_template("index.html", quote=quote, tittle=tittle)
  
  
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)    



@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form) 


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))       

@main.route('/blogs')
@login_required
def blogs():
    all_blogs = Blog.query.order_by(db.desc(Blog.created_at)).limit(15)

    return render_template('blogs.html', all_blogs=all_blogs)

@main.route('/post/<int:post_id>')
@login_required
def post(post_id):
    post = Blogpost.query.filter_by(id=post_id).first()

    return render_template('post.html', post=post)



@main.route('/deleteblog/<int:id>', methods=['GET', 'POST'])
@login_required
def deleteBlog(id):
    blog = Blog.query.get_or_404(id)
    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for('main.blogs'))   

@main.route('/update/<int:id>', methods=['GET', 'POST'])
@login_required
def updateBlog(id):
    blog = Blog.query.get_or_404(id)
    form = BlogForm()
    if form.validate_on_submit():
        blog.title = form.title.data
        blog.content = form.content.data
        db.session.add(blog)
        db.session.commit()

        return redirect(url_for('main.blogs'))
    elif request.method == 'GET':
        form.title.data = blog.title
        form.content.data = blog.content
    return render_template('updateBlog.html', form=form)    


@main.route('/post')
def add():
    return render_template('post.html')

@main.route('/addblog', methods=['GET','POST'])
@login_required
def addpost():

    form =  PostForm()

    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data

        new_blog = Blog(title=title,
                        content=content, user=current_user)

        new_blog.save_blog()
        return redirect(url_for('main.index'))

    return render_template('new_blog.html', form=form)




@main.route('/comment/new/<int:id>', methods=['GET', 'POST'])
@login_required
def new_comment(id):
    form = CommentForm()
    
    blog = Blog.query.filter_by(id=id).first()
    blogComments = Comment.query.filter_by(blog_id=id).all()
    if form.validate_on_submit():
        content = form.comment.data

        new_comment = Comment(
            blog_id=blog.id, content=content, user=current_user)

        new_comment.save()
        print(new_comment)
        # return redirect(url_for('main.index'))

    return render_template('new_comment.html', comment_form=form,blog_comment=blogComments)

@main.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def deleteComment(id):
    comment =Comment.query.get_or_404(id)
    db.session.delete(comment)
    db.session.commit()
    
    return redirect (url_for('main.blogs'))    

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% if comments %}
{% for comment in comments %}
<div class = "card-panel">
    <p>{{ comment.content}}</p>
    <p class = "right-align grey-text"> By {{ comment.user.username }}</p>
</div>
{% endfor %}
{% else %}
<div class = "card-panel">
    <p>No commments on this blog</p>
</div>
{% endif %}
<br>

app/templates/blogs.html
{% extends 'base.html' %}

{% block content %}

<div class = "valign-wrapper">
<div class = "container">
    <div class="row">
    <div class="col l3 m3 s12"></div>
    <div class="col l6 m6 s12">
    <br>
    {% for blog in all_blogs%}
    <h1>{{blog.title}}</h1>
    <p class="black-text">By {{blog.user.username}}</p>
    <p>{{blog.content}}</p>
    <br><hr><br><br>
     <a href="{{url_for('main.new_comment', id=blog.id)}}">comment</a>
     <a href="{{url_for('main.deleteBlog',id = blog.id)}}">delete blog</a>
     <a href="{{url_for('main.updateBlog',id = blog.id)}}">update blog</a>
    {% endfor%}
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block
    styles%} {{ super() }}
    <link rel="stylesheet" href="../static/css/index.css" />
    {% endblock %} {% block content %}
    
    <body>
        <br /><br />
        <br />
        <div class="container">
            <h3 style="text-align: center;">Take a look at New Comments</h3>
            {% for comm in comment[::-1] %}
            <div class="col-sm">
                <div class="well well-lg p-3" id="card" style="text-align: center">
    
                    <hr />
    
                    <div class="card col-sm mt-2">
    
                        <h4 class="card-title">{{comm.author}}</h4>
                        <p class="card-text">{{comm.comment}}.</p>
    
                        <div class="card-footer bg-transparent border-success">
                            <small>Publish date:{{comm.date_posted.strftime('%Y-%m-%d')}}</small>
    
                        </div>
                        <a href="{{url_for( 'main.deleteComment', id= comm.id)}}"><button>delete</button></a>
                    </div>
                    <br>
    
                </div>
    
    
            </div>
    
            {% endfor %}
        </div>
        </div>
    </body>
    
    {% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="valign-wrapper ba-jumbotron">
    <div class="container center-align">
        <h2>Maalim's Blogs</h2>
        
    </div>
</div>
<div class="container">
    
    <hr>
    <br>
    <p class="center" style="font-size: 30px;">{{quote.quote}}</p>
    <p class="center" style="font-size: 30px;"><strong>Author: </strong>{{quote.author}}</p>
    <div class="row">
      
    </div>
</div>
 <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <p >Copyright &copy; Maalim2021</p>
            </div>
          </div>
        </div>
      </footer>
      {% endblock %}

  
    

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/blogs"> blogs </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li><a href="{{url_for('main.addpost')}}" rel="noopener noreferrer">
                      Add a Blog
                  </a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}"><span class="glyphicon glyphicon-user"></span>Sign in</a></li>
                  {%endif%}
                </ul>
            </div>

        </div>
    </div> 


    
   
  </body>
</html>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
    <div class="container">

        

        <div class="col-md-4">

        </div>

        <div class="col-md-4">

            <h1>CREATE A POST</h1>
            <br>
            {{ wtf.quick_form(form) }}
        </div>

        <div class="col-md-4">

        </div>

    </div>

{% endblock %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="col-md-8">
            {{blogs}}
        </div>
        <div class="col-md-4">
                <h3 class="text-center">leave a comment</h3>
            {{ wtf.quick_form(comment_form) }}
        </div>


        <div class="col-md-4">
            <h3 class="mt-3 pb-3">Comments</h3>
            <hr>
            {%for comment in blog_comment[::-1]%}
            <p>{{comment.content}}</p>
            
            <p> By: {{comment.user.username}}</p>            
            <a href="{{url_for('main.deleteComment',id = comment.id)}}">delete</a>
            {%endfor%}
    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit  your profile</a>
{% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/updateBlog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8 mt-3 p-5">
    <h3 class="mt-3 pb-3 text-center">Update Blog</h3>
    <hr>
{{wtf.quick_form(form)}}
</div>
<div class="col-md-2">
</div>
</div>
</div>
{% endblock%}

app/templates/user_post.html
{% extends "blog.html" %} 

{% block content %}
<p>Posts by {{ user.username }} ({{ posts.total }})</p>

{% for post in posts.items %}

    {{ post.author.username }} {{ post.date_posted.strftime('%Y-%m-%d') }}
    {{ post.title }}
    {{ post.content }}

{% endfor %} 
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

    {% if page_num %} 
        {% if posts.page == page_num %} 
            {{ page_num }} 
        {% else %} 
            {{ page_num }}
        {% endif %}
     {% else %} 
        ...

    {% endif %} 

{% endfor %} 
{% endblock content %}